---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
  labels:
    app: timber-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timber-backend
  template:
    metadata:
      annotations:
        ready: "true"
        url: "https://github.com/tektoncd/pipeline/tree/master/cmd/entrypoint"
      labels:
        app: timber-backend
    spec:
      volumes:
      - name: podinfo
        downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['ready']
            path: ready
      containers:
      - name: timber-backend
        image: lalyos/lunch-wto
        readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 1
            exec:
              command:
                - "sh"
                - "-c"
                - "grep true /etc/podinfo/ready"
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
        ports:
        - containerPort: 8080
        resources: {}
